### ISSUE TITLE
NoSuchMethodError: java.lang.Integer.compare(II)I

### ISSUE THREAD

**Issue by mdhoenig** [tabulapdf/tabula-java#106]
Ever since updating to 0.9.1, I get this error:

```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Integer.compare(II)I
	at technology.tabula.TextChunk.isLtrDominant(TextChunk.java:179)
	at technology.tabula.TextElement.mergeWords(TextElement.java:266)
	at technology.tabula.TextElement.mergeWords(TextElement.java:105)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:118)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.extract(SpreadsheetExtractionAlgorithm.java:86)
	at technology.tabula.extractors.SpreadsheetExtractionAlgorithm.isTabular(SpreadsheetExtractionAlgorithm.java:153)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:152)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:60)
```

The PDF table in question works fine with 0.9.0 and previous versions.  Only command line parameter I was using was "-p all" (but it crashes without it too).  Can anyone help?

This on Mac OS 10.8.5.  Here is my Java info:

```
> java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)
```

Thanks.

**Comment by jazzido** [comment]
Hi @mdhoenig,

`tabula-java` only supports Java 1.7 and up.  It should work fine if you update your JVM.

Thanks!
